---
# Akamai provider that references the secret credentials
apiVersion: akamai.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: akamai-credentials
      key: edgerc